### PR TITLE
Publish apk artifacts when pushing a new version

### PR DESCRIPTION
**Pull request by HamletDuFromage**
Hello,
The app is not available on f-droid and it seems like foreigners can't get it from the Play Store either. I could only find it on third-party websites and even then the most reputed ones (apkmirror for instance) didn't have it. I know this is a debug release but I believe it's better than nothing, at least it's from a trusted source.
Besides Google Play complaining about the app coming from an unknown source, it seems to be working well enough https://github.com/HamletDuFromage/covpass-android/actions/runs/1020670532

## Checklist

- [x] The CHANGELOG is up to date with public API changes.
- [x] The documentation is up to date and in a good shape.
- [x] The unit tests for new code I've added are in a good shape.
- [x] These changes are compatible with R8/ProGuard.

### CODE REVIEW

**Review by olof-nord — APPROVED** [review]

**Comment by wkornewald** [comment]
Thanks for your contribution. Some reasons why this hasn't been approved yet:

* This is only uploading the debug builds - not yet sure if this is enough as a first step and since they log quite a bit of data, sensitive information could land in the logs which means we have a security issue if we provide these builds "officially". At least people seem to want an APK download they can use in practice and this means debug builds are not an option.
* We need to clarify how signed release APKs could get published here - and this might mean we can't use this GitHub repo's pipeline, but need a separate, secured environment.
* It would be nice to create a GitHub release entry for each version tag and have the APKs live there.

**Comment by github-tomster** [comment]
> ...
> * This is only uploading the debug builds - not yet sure if this is enough as a first step and since they log quite a bit of data, sensitive information could land in the logs which means we have a security issue if we provide these builds "officially". At least people seem to want an APK download they can use in practice and this means debug builds are not an option.

@thosetryingtocode
looking at the mess done here https://github.com/Digitaler-Impfnachweis/covpass-android/issues/28 i appreciate @HamletDuFromage's approach
to do the repositoryowners job 👎🏻  providing something better than nothing!


> * We need to clarify how signed release APKs could get published here - and this might mean we can't use this GitHub repo's pipeline, but need a separate, secured environment.

nice to see there is some 'kind of thinking about' this essential point 🤦🏻‍♂️ 

> * It would be nice to create a GitHub release entry for each version tag and have the APKs live there.

are you trying to invent the wheel again ❓ 💢 
all those repositories seem to be a miracle 🧙🏻‍♂️ 

you state https://digitaler-impfnachweis-app.de/technische-details :
- Keine zentrale Datenhaltung / no centralized datacollection
- Abgesicherte Kommunikationswege / secured communicationchannels
- Datensparsamkeit / dataefficiency
- Vertrauensvoll und sicher / trustworthy and secure

and **FORCiNG** the users to use google play store, this is ridiculous 🤦🏻‍♂️ 🔫 

unfortunately the roadmap looks like:  we have no skills but google can do it for us 💩 

but hey, lean back, relax, youre in good company with this strategy 🤡

**Comment by andycandy-de** [comment]
Creating and signing a release APK shouldn't be a problem with Github actions. Simply configure the app release and signing in the Gradle build scripts.
https://newbedev.com/android-studio-how-to-generate-signed-apk-using-gradle

To protect the certificate, you can use GitHub secrets.
https://proandroiddev.com/how-to-securely-build-and-sign-your-android-app-with-github-actions-ad5323452ce

Or, create and publish the app to a secure environment. There must be an official, open source to download the APK. It's not okay to force users to use a commercial app store. Acually it's not possible to download the APK without google account. This' s unacceptable.

**Comment by HamletDuFromage** [comment]
> Creating and signing a release APK shouldn't be a problem with Github actions. Simply configure the app release and signing in the Gradle build scripts.
> https://newbedev.com/android-studio-how-to-generate-signed-apk-using-gradle
> 
> To protect the certificate, you can use GitHub secrets.
> https://proandroiddev.com/how-to-securely-build-and-sign-your-android-app-with-github-actions-ad5323452ce
> 
> Or, create and publish the app to a secure environment. There must be an official, open source to download the APK. It's not okay to force users to use a commercial app store. Acually it's not possible to download the APK without google account. This' s unacceptable.

It's actually available on f-droid now, so publishing the APK on GitHub isn't that big of deal anymore

**Comment by andycandy-de** [comment]
> It's actually available on f-droid now, so publishing the APK on GitHub isn't that big of deal anymore

The f-droid CovPass Check App is not up to date! An actual CovPass and CovPass Check release must be available on a official, open source (e.g. attached to github tags, at the https://digitaler-impfnachweis-app.apps.public.bfarm.de/ homepage or in the f-droid store)

This app is implemented for general public and must be available for everyone without the requirement to have a google or huawei account!

**Comment by HamletDuFromage** [comment]
Ah, I wasn't aware it isn't up to date. Then yeah, it should definitely be made available outside of the Playstore, especially considering the nature of the app

**Comment by github-tomster** [comment]
NO! the app is not available at f-droid.
there was some private effort made to port this repo to gitlab
 `FOSS version of the official CovPass(-Check) Android apps and SDK` 
`upstream: https://github.com/Digitaler-Impfnachweis/covpass-android`

it makes no sense to think an upper-level federal agency can handle such a project 🤡

**Comment by pucherd** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to be available until 31 December 2023.

From 1 January 2024:

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.

**Pull request closed without merging**
