### PR TITLE
Feature/fix autofocus

### LINKED ISSUE #114: Cant scan QR code - No Autofocus (Lineageos / AOSP)
## Avoid duplicates
* [ X ] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [ X ] Bug is not already reported in another issue

## Technical details

- Device name: SM-G900F
- OS version: LineageOS 7.1.2
- App version: 1.13.2

## Describe the bug

Not able to scan the code. 
Camera does not auto-focus in Android CovPass Check App when scanning the code. 
In other Apps (like CWA or Camera) the Camera auto-focuses without problem.

## Steps to reproduce the issue
Install the App on Android 7.1.2 and try to scan a code

## Expected behaviour

Camera autofocuses when scanning the code.
## Possible Fix

Continously - or tap-to-focus -autofocus the camera when scanning.
## Additional context
Section:Tap-To-Focus
https://proandroiddev.com/android-camerax-tap-to-focus-pinch-to-zoom-zoom-slider-eb88f3aa6fc6

https://gist.github.com/husaynhakeem/1eec93bc18ff863ae84c0acb6d406ac8#file-camerax_tap_to_focus-kt

### PR DESCRIPTION
**Pull request by chlorophyll-zz**
Fixes #114
@oltdaniel 

## Ticket id

EBH-

## Checklist

- [ X ] The CHANGELOG is up to date with public API changes.
- [ X ] The documentation is up to date and in a good shape.
- [ ] The unit tests for new code I've added are in a good shape.
- [ ] These changes are compatible with R8/ProGuard.

### CODE REVIEW

**Comment by wkornewald** [comment]
Thanks a lot for your contribution. Would you also have time to implement continuous auto-focus, so the user doesn't even have to explicitly tap anywhere? Tap-to-focus is mostly useful if you're doing creative photos, but for QR-code readers there's probably no need for this as the target is always more or less in the center anyway.

**Comment by oltdaniel** [comment]
> Thanks a lot for your contribution. Would you also have time to implement continuous auto-focus, so the user doesn't even have to explicitly tap anywhere? Tap-to-focus is mostly useful if you're doing creative photos, but for QR-code readers there's probably no need for this as the target is always more or less in the center anyway.

Agreed. I would probably choose the `java.util.Timer` with a fixed rate `TimerTask` where the autofocus auto cancel is `x` and the interval of the new autofocus `x + 1`.

Any comments on that?

**Comment by chlorophyll-zz** [comment]
> Thanks a lot for your contribution. Would you also have time to implement continuous auto-focus, so the user doesn't even have to explicitly tap anywhere? Tap-to-focus is mostly useful if you're doing creative photos, but for QR-code readers there's probably no need for this as the target is always more or less in the center anyway.

@oltdaniel is the contributor. I only did the PR. I dont know if he is still available. 
When he is not availabe, this is better than no auto-focus at all, like before. 
Also, many people are used to tapping the picture to focus, that was also my first intention, 
until I realized that no auto-focus was availabe. 

The added feature works as expected. Can you just add it, instead of waiting for another contribution?
The App now works way better than before. 

@oltdaniel I think the Camera Parameter has to be set to FOCUS_MODE_CONTINUOUS_PICTURE:
https://developer.android.com/reference/android/hardware/Camera.Parameters#FOCUS_MODE_CONTINUOUS_PICTURE

Then we would have to test wether an initial autofocus is enough.

**Comment by wkornewald** [comment]
Maybe @oltdaniel you should then create a new PR, so your name is also in the squash merged commit? And yes, continuous mode as described by @chlorophyll-zz would be best.

And while it's not needed here, instead of a Timer we'd use a coroutine with a while(true) loop and delay() because that gets destroyed automatically when you leave the screen and you can easily make it lifecycle-aware and you can model even complicated rules in a more readable and less error-prone way (so it scales better).

**Comment by oltdaniel** [comment]
@chlorophyll-zz COuld you please close this PR so I can open one myself?



> ...
> And while it's not needed here, instead of a Timer we'd use a coroutine with a while(true) loop and delay() because that gets destroyed automatically when you leave the screen and you can easily make it lifecycle-aware and you can model even complicated rules in a more readable and less error-prone way (so it scales better).

Thank you for the information. It has been 3-4 years since I last touched Android Development. However, I disagree to use the mentioned FOCUS_MODE_CONTINUOUS_PICTURE. The QRCodeScanner in this App uses `androidx.camera.core` which does not offer this kind of functionality. Additionally, that option is marked as deprecated.

So there is further discussion needed. There are multiple solutions here:
- **Using a Co-routine**: Although this is not a good way, there is an option in the end.
- **Continous Autofocus with Callbacks**: The `.startFocusAndMetering` returns an Listenable after the measurement is done. Somewhere there should also be an `.afterMeasured` function in some Preview class, where we could move the `startFocusAndMetering` calls.

**Being resonable**. As this is just a small fixed I implemented, I don't want to spend hours on supporting an device from 2014. Maybe ask the boys and girls over at `CoronaWarnApp` how they solved this, because in their App this function works just fine. I agree, that QR Code Scanning should have automatic focus, I don't see the return for the time investment. So I'll create a new PR and the actual developers of this App can continue the work,

**Comment by chlorophyll-zz** [comment]
> @chlorophyll-zz COuld you please close this PR so I can open one myself?
Of course.

I value the working autofocus and tap-to.focus in the CovPass Check app on my (our) device, thanks to your work.

**Comment by chlorophyll-zz** [comment]
@oltdaniel
I find it dramatic that the app misses autofocus from the start, so please open the PR.

**Pull request closed without merging**
